### PR TITLE
Added "ltc!rate#xx" command

### PR DESCRIPTION
**Pull request by hippyau**
Hi Arjan!

I've added the ability to change FPS via UDP message.   
eg.  `echo 'ltc!rate#30' | nc -u -p 21571 -w 1 192.168.1.82 21571`

I am a newbie at the git and pull request stuff, so please bare with me...  I need to import your changes via command line and I am fudging my way through it....  

Anyway,  I have a bunch of stuff in my fork, related to my WS28xx display, firmware compression and the ltc!rate# command.   My WS82xx display is working now, but still a work in progress.
Firmware compression is working great :) and ltc!#rate seems to work fine. 

I'm not a pro C++ programmer like yourself,  and im struggling to understand the file.txt and mask and storing config options, but we'll get there!

Anyway, you might like to pluck out the ltc!rate stuff.

### CODE REVIEW

**Comment by vanvught** [comment]
Hi Hip, this is really great work. Thanks! I am using Github basically just for backup and some own version management. My local repository is also some commits ahead from the web. So I need to do some conflict resolving before I can merge your changes.

When you are on FB, then please post your WS28xx display here https://www.facebook.com/groups/lxdesigners/?ref=group_header and here https://www.facebook.com/groups/584412254990472/

Groeten, Arjan

**Comment by hippyau** [comment]
No worries Arjan!  I still have work to do on the clock i've built,  but hopefully the ltc!rate# stuff should be easy to get at :)  I want to get better at pull/merge stuff, I should read more!

**Comment by hippyau** [comment]
haha, Thanks Arjan.   No rush on the WS28xx code, still very hacky and not really finished.   I will keep working on it though.

**Comment by vanvught** [comment]
Hi Hip, I have introduced a new class LtcOutputs (https://github.com/vanvught/rpidmx512/blob/master/lib-ltc/src/h3/ltcoutputs.cpp). This class is responsible for all display types of output. And is also responsible for MIDI output.
You just need to uncomment this line https://github.com/vanvught/rpidmx512/blob/master/lib-ltc/src/h3/ltcoutputs.cpp#L121 for enabling your display.
The configuration enabling for your display is in here https://github.com/vanvught/rpidmx512/blob/master/lib-ltc/src/ltcparams.cpp#L317
When I have done everything well, then you just have to commit your displayws28xx.h  and displayws28xx.cpp files

**Comment by hippyau** [comment]
Sorry, been so busy, and now I'm sooo lost...
I'm going to fresh fork and insert my ws28xx code :)

**Comment by vanvught** [comment]
> and now I'm sooo lost...

That's not good ;-)

**Pull request closed without merging**
