### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by vanvught**

### CODE REVIEW

**Comment by vanvught** [comment]
Hi Hippy, 
Before merging all our code to the master branch, I will make the change for disabling LTC output when WS28xx is enabled. This should be a temporarily work-around until I have SPI DMA implemented. 
Greetings, Arjan

cc: @hippyau

**Comment by hippyau** [comment]
Hi Arjan!

Today didn't work out for me how I'd hoped.  I'll pull fresh
hopefully tomorrow night, build clean and test.

I had noticed the very slight and occasionally flicker of one segment, and
it seemed to be the same segment flickering but a sometimes different
segment number flickering each boot, I put it down to my RS485 setup, as I
didn't notice that until before close to the end of my build.

I'm so glad you know the architecture well!  Setting up a DMA transaction
for SPI is the go one day! ;)

I can see all your improvements, and excited to test!  Thanks for your hard
work!  :)

I also got some of those ws2812 8x8 led matrix boards which I am going to
play with over XMAS, so we may end up with another type of ws2812 display
soon.  Also building a clone of the one I've already made, but with
different LED strip type (1 LED per chip, not 3 LED per chip), to test the
ability to change types in the software.

Cheers,
  Hippy

**Comment by hippyau** [comment]
Hi Arjan!!

It seems to be working great!   The flicker is gone as LTC is disabled.

I have only two problems:

I can't remember how to get the Time of Day as the source.   :)

I can't test the latest UI because I can't compile the .java code or get it to start from the bin/.class files you've provided... very embarrassing for me, i've tried a several different things I googled, but I don't understand what I need to be doing properly for this app....   does your IDE give a command line used to make the jar? 

I got so far as making a .jar file from the class files in the bin directory, but it wouldn't run because a of missing manifest and i'm just too frustrated with it now, hahaha... 
i'd love to make a script that would build the jar.

But functionally, it seems stable, TC running for 24hr ok.

Cheers,
  Hip

```
U-Boot SPL 2017.03-rc2-00252-gc987c17120-dirty (Oct 26 2019 - 15:37:55)
DRAM: 256 MiB
Trying to boot from sunxi SPI


U-Boot 2017.03-rc2-00252-gc987c17120-dirty (Oct 26 2019 - 15:37:55 +0200) Allwinner Technology

CPU:   Allwinner H3 (SUN8I 1680)
Model: Xunlong Orange Pi Zero
DRAM:  256 MiB
MMC:   SUNXI SD/MMC: 0
spi_flash_decode_fdt: Cannot decode address
SF: Detected mx25l1605d with page size 256 Bytes, erase size 64 KiB, total 2 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   phy interface0
eth0: ethernet@1c30000
starting USB...
USB0:   USB EHCI 1.00
USB1:   USB OHCI 1.0
scanning bus 0 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
spi_flash_decode_fdt: Cannot decode address
SF: Detected mx25l1605d with page size 256 Bytes, erase size 64 KiB, total 2 MiB
device 0 offset 0x180000, size 0x22000
SF: 139264 bytes @ 0x180000 Read: OK
## Booting kernel from Legacy Image at 48000000 ...
   Image Name:   http://www.orangepi-dmx.org
   Image Type:   ARM U-Boot Standalone Program (gzip compressed)
   Data Size:    82919 Bytes = 81 KiB
   Load Address: 40000000
   Entry Point:  40000000
   Verifying Checksum ... OK
   Uncompressing Standalone Program ... OK
MX25L1605D, sector size 4096, 2097152 bytes
Detected MX25L1605D with sector size 4096 total 2097152 bytes
[V2.2] Orange Pi Zero Compiled on Dec 11 2019 at 21:55:34
Network init
Network
 Hostname : allwinner_1F0393
 If       : 1: eth0
 Inet     : 192.168.1.56 /24
 Netmask  : 255.255.255.0
 Gateway  : 192.168.1.1
 Mac      : 02:42:08:1f:03:93
 DHCP     : Yes
NTP v4 Client
 Server : 192.168.1.1
 Port : 123
 Status : 1 
 Time : Wed Dec 11 22:02:23 2019
 UTC offset : 36000 (seconds)
Setting Node parameters
Starting the Node
Node 3
 Firmware   : 1.40
 Short name : LTC SMPTE Node
 Long name  : Orange Pi Zero Art-Net 3 www.orangepi-dmx.org
Node started
Internal
 EBU 25fps  
 Start : 00.00.00:00
 Stop  : 23.29.59:24
TCNet
 Node : AvV-OPi
 Using SMTPE fields
 30 FPS
MIDI
 Direction    : Output
 Active sense : Disabled
 Baudrate     : 31250 (Default)
 Interface    : UART2
mDNS
 Name : allwinner_1F0393.local
 _apple-midi._udp.local 5004 
 _config._udp.local 10501 
AppleMIDI
 SSRC    : c0a80138 (3232235832)
 Session : allwinner_1F0393
Display WS28xx
 8 Digit(s), 3 Colons, 62 LED(S)
 Type    : WS2812B [3]
 Mapping : RGB [0]
 Master  : 255
Source : Internal
 LTC output is disabled
 NTP output is disabled
 Max7219 output is disabled
Display : -1 (0,4)
```

**Comment by vanvught** [comment]
[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/3950368/RemoteConfigUI.jar.zip)

cc: @hippyau

**Comment by vanvught** [comment]
> I can't remember how to get the Time of Day as the source. :)

`source=systime`

**Comment by hippyau** [comment]
Of course!  


> > I can't remember how to get the Time of Day as the source. :)
> 
> `source=systime`

Thanks Arjan... sorry it's been a few days.

It didn't like that at all, I get one blue segment (same as at power-on).

I'll investigate further...

```

[V2.2] Orange Pi Zero Compiled on Dec 11 2019 at 21:55:34
Network init
Network
 Hostname : allwinner_1F0393
 If       : 1: eth0
 Inet     : 192.168.1.56 /24
 Netmask  : 255.255.255.0
 Gateway  : 192.168.1.1
 Mac      : 02:42:08:1f:03:93
 DHCP     : Yes
NTP v4 Client
 Server : 192.168.1.1
 Port : 123
 Status : 1 
 Time : Wed Dec 11 22:53:26 2019
 UTC offset : 36000 (seconds)
Setting Node parameters
Starting the Node
Node 3
 Firmware   : 1.40
 Short name : LTC SMPTE Node
 Long name  : Orange Pi Zero Art-Net 3 www.orangepi-dmx.org
Node started
Internal
 EBU 25fps  
 Start : 00.00.00:00
 Stop  : 23.29.59:24
TCNet
 Node : AvV-OPi
 Using SMTPE fields
 30 FPS
MIDI
 Direction    : Output
 Active sense : Disabled
 Baudrate     : 31250 (Default)
 Interface    : UART2
mDNS
 Name : allwinner_1F0393.local
 _apple-midi._udp.local 5004 
 _config._udp.local 10501 
AppleMIDI
 SSRC    : c0a80138 (3232235832)
 Session : allwinner_1F0393
Display WS28xx
 8 Digit(s), 3 Colons, 62 LED(S)
 Type    : WS2812B [3]
 Mapping : RGB [0]
 Master  : 255
Source : System-Time
 LTC output is disabled
 NTP output is disabled
 Max7219 output is disabled
Display : -1 (0,4)

```

**Comment by hippyau** [comment]
> Of course!
> 
> > > I can't remember how to get the Time of Day as the source. :)
> > 
> > 
> > `source=systime`
> 
> Thanks Arjan... sorry it's been a few days.
> 
> It didn't like that at all, I get one blue segment (same as at power-on).
> 
> I'll investigate further...
> 
>

Of course, I must tell it to start!  systime confirmed working!

**Comment by vanvught** [comment]
Op 11 dec. 2019 om 13:57 heeft Hippy <notifications@github.com> het volgende geschreven:
> 
> ﻿
> Of course!
> 
> I can't remember how to get the Time of Day as the source. :)
> 
> source=systime
> 
> Thanks Arjan... sorry it's been a few days.
> 
> It didn't like that at all, I get one blue segment (same as at power-on).
> 
Hi Hippy, please check the .txt file in the Java UI. The properties struct is now packed; that might cause an issue when it is already has been used. A re-save could do the job.

Greets, Arjan

**Comment by hippyau** [comment]
Arjan, you have out done yourself.

Using your RemoteUI you just sent... everything is awesome!
I have my display working perfectly now, thanks for the led_rgb_mapping setting :) 

The colons are fading in now though, I prefered them fading out...  I will learn and add this setting to ldisplay.txt :)  I will also change my defines to runtime configurable variables for the LEDS_PER_SEGMENT etc, so to make more maker friendly.  But not holding up V2.2!

Only "bug/feature" I can see that source=systime does not auto start on boot.  


My settings are: 

#rconfig.txt
enable_reboot=1
enable_uptime=1

#network.txt
ip_address=192.168.1.82
net_mask=255.255.255.0
default_gateway=192.168.1.1
ntp_server=192.168.1.1
ntp_utc_offset=10.0
display_name=BigTC

#ltc.txt
source=systime
disable_max7219=1
disable_ltc=1
show_systime=1
ws28xx_enable=1

#ldisplay.txt
led_type=WS2812B
led_rgb_mapping=RBG

Very happy with this build now that i've configured it.   I'll work on documentation as I can.
I am building another clock with different tape and such soon.    WS28xx LED's over RS485 works so well!!

Cheers you legend, thanks Arjan!

Cheers again,
 hippy.

**Comment by hippyau** [comment]
I do wonder, can we 'soft-reset' by jmp to not_main()?   that might speed up source change?
It's not a biggie to wait ten seconds for full reboots, just thought as a speed up to source selection buttons?    Just a thought for V3

**Comment by vanvught** [comment]
> does your IDE give a command line used to make the jar?

Hi Hip, 
I am using Eclipse (CDT) and then I can simply export an runnable .jar file.
Groet, Arjan

**Comment by hippyau** [comment]
I'll give it a try...
Thanks man, so happy :)

**Comment by vanvught** [comment]
> The colons are fading in now though, I prefered them fading out... I will learn and add this setting to ldisplay.txt :) 

See commit 483ca8f ;)

**Comment by vanvught** [comment]
>  WS28xx LED's over RS485 works so well!!

Maybe we should create a page under http://www.orangepi-dmx.org/orange-pi-dmx512-rdm/ws28xx-configuration explaining this long-range RS385 ?

**Comment by vanvught** [comment]
Closing this one. Creating a new one.

**Pull request closed without merging**
