### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by hippyau**
Initial ltc shell commands.

Sorry, didn't mean to do to main.

### CODE REVIEW

**Comment by vanvught** [comment]
Hi Hippy, please see my comment here -> https://github.com/vanvught/rpidmx512/issues/126#issuecomment-668584514
Looks like we can leave the lib-etc untouched. Greetings, Arjan

**Comment by hippyau** [comment]
moved 'ltc!' header back into the shell specific code, so as to have minimal impact on existing HandleUdpRequest() code into HandleRequest( with optional \0 terminated string command here).

**Comment by vanvught** [comment]
> This branch has conflicts that must be resolved
Conflicting files
lib-ltc/src/h3/ltcgenerator.cpp
lib-ltc/src/h3/systimereader.cpp

Please make sure you have the latest code from GitHub.

**Comment by vanvught** [comment]
I am not sure why we need to echo the UART; any serial terminal has the option for local echo. Moreover, as the shell can be used in run-time, we are introducing a scary blocking wait -> https://github.com/vanvught/rpidmx512/blob/master/lib-h3/src/h3_uart0_debug.c#L83

**Comment by hippyau** [comment]
Hey Arjan, is certainly optional,  I only include as compile time option for development ease,  it can be left out or disable by default, but I found very useful and provides a "telnet-like" experience and I can tell it is working straight away when connecting wires to the board because it echos back to me.  When playing with u-boot and echo is on in the terminal software, I get double echo from the oPi :)

**Pull request merged**
