### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by hippyau**
Added a smaller 5x8 font.

Started to add a colour setting for the TC RATE line, but got stuck because I need to learn more C++,  overrides.

Plan to add an animated icon next to TC RATE to show running/direction

Thoughts?

### CODE REVIEW

**Comment by hippyau** [comment]
Shit, sorry... only meant to be [this commit](https://github.com/vanvught/rpidmx512/pull/158/commits/8aac63b1e777de8c643fb8f39edc0f5681b37502) beyond.   Not sure what i've done here :)

**Comment by vanvught** [comment]
@hippyau 
There are 41 files changed, files which should be changed. I cannot merge this request.

**Comment by hippyau** [comment]
Understood, I screw up :)

**Comment by vanvught** [comment]
Geen probleem! :-)

**Pull request closed without merging**
