### PR TITLE
Add WS28xx Display

### PR DESCRIPTION
**Pull request by hippyau**
Hi Arjan,

 I worked it out, I added my WS28xx code to a fresh clone (tonight) of your master.
 This brings us up-to-date.

I had to add lib-nextion to be able to compile the fresh copy,  not sure how to address that. (lib-nextion pulled fresh today, compiled fine)

I also had to add WS28XX_UNDEFINED to ws28xx.h as it was missing and I could find no reference.

I have two scripts I found helpful, so I added them too.

PS.  This is WS28xx display working now, i've still got to do the write up.

Kind Regards,
  Hippy

### CODE REVIEW

**Comment by vanvught** [comment]
Hi Hippy, I will merge this request in the weekend. Groet, Arjan

**Comment by hippyau** [comment]
hi Arjan,

Most of the pull request is chewed up by having to add lib-nextion to be able to compile sorry,  this is exact copy from your other repo yesterday.

I've just added a '`ltc!showmsg#hi arjan`' which temporarily shows a message in a selected colour and then fades it out back to time code.   Currently, if message is > 11 bytes (8 digits, 3 colons) then it's dropped completely, otherwise arbitrary length works and message is displayed.  (might add scrolling for longer messages in future).

I figure be good for source selection too, to show `'Ltc', 'nIDI', 'TCnEt'`... well, maybe :) haha.

Also added `ltc!rgb#200FF00` where the `2` is an index of colour settings (`0` being segments, `1` being colons, and `2` being messages).... the rest of the line is RRGGBB in hex. 
ie:  
set segment colour red = `#0FF0000`,
set colon colour green = `#100FF00`, 
set message colour blue = `#20000FF`

We have good functionality now, so I'll start documenting it soon. 

Cheers,
 hip

**Comment by vanvught** [comment]
Hi Hip,

Basically I've messed up this repository by adding (and committing) -> https://github.com/vanvught/rpidmx512/blob/master/h3-firmware-template/Rules.mk#L146

The prototype development for the Nextion HMI display's should only be done here -> https://github.com/vanvught/opi-nextion

I will fix this compile issue.

Groet, Arjan

**Comment by hippyau** [comment]
Hey Arjan,
  That was easier than I thought!  Now on port 10258 (0x2812).
Cheers,
 Hip

**Comment by vanvught** [comment]
Hi Hip - great!

I am about to finish testing the NTP Client. I have also included the NTP Client into the monitor's firmware.  

It is all getting close to perfect ;-)

Groeten, Arjan

**Comment by hippyau** [comment]
Awesome!   I just removed lib-nextion from my fork, but had to drop src/storenextion.cpp from libspiflashinstall also to get to compile cleanly.

**Comment by vanvught** [comment]
> but had to drop src/storenextion.cpp

Ah..yes, that one should also not be there. I will drop it is well.

**Comment by vanvught** [comment]
> Now on port 10258 (0x2812).

Created new page -> http://www.orangepi-dmx.org/orange-pi-smpte-timecode-ltc-reader-converter/ws28xx-7-segment/run-time-udp-messages

**Comment by hippyau** [comment]
Thanks Arjan, I've populated both pages.  Not quite perfect yet, but the bulk in there.

Cheers ;)

**Comment by vanvught** [comment]
Hi Hip,

Please will you test branch https://github.com/vanvught/rpidmx512/tree/staging ? 

This branch includes your code with also the support for NTP Client. 

Greetings, Arjan

**Comment by hippyau** [comment]
Your staging branch works great, thanks Arjan.  I'll close this pull request.  

I can now properly contain my changes, so next pull request will be exclusively about the WS28xx Display. 

Cheers!

**Pull request closed without merging**
